# iftDataSet NumPy Interface

In [1]:
import pyift as ift
import numpy as np

Initializing values for the example

In [2]:
n_samples = 50
n_features = 10

X = np.zeros((n_samples, n_features), dtype=np.float32)
Y = np.zeros(n_samples, dtype=np.int32)

There are four ways that we can create a iftDataSet in Python, memory is deallocated automatically by the Python garbage collector

In [3]:
Z_1 = ift.CreateDataSetFromNumPy(X, None) # from a numpy array without label

Z_2 = ift.CreateDataSetFromNumPy(X, Y) # from a numpy array with label

Z_3 = ift.CreateDataSet(n_samples, n_features) # with the ift function

Z_4 = ift.ReadDataSet('iftDataset.zip') # reading a already existing iftDataSet

Also, it is possible to access the internal values of the iftDataSet with the functions below,
every method returns a copy of the original C data, to modify each internal C struct data it is necessary to use their respective method.

In [4]:
Z_2.GetData()

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 

In [5]:
Z_2.GetLabels()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=int32)

In [6]:
Z_2.SetLabels(np.ones(n_samples, dtype=np.int32))
Z_2.GetLabels()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int32)